In [11]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
benzersiz_notlar = list(set(notlar))
print("benzersiz liste,",benzersiz_notlar)

buyuk = max(notlar)
kucuk=min(notlar)
print("en büyük: ",buyuk)
print("en küçük:",kucuk)

sirali_notlar = sorted(notlar)
print("sirali notlar ",sirali_notlar)

benzersiz liste, [100, 92, 85, 76]
en büyük:  100
en küçük: 76
sirali notlar  [76, 76, 85, 85, 92, 92, 92, 100]


In [13]:
def armstrong(sayi):
  basamak=str(sayi)
  toplam=0
  for rakam in basamak:
    toplam +=int(rakam)**3

  return toplam == sayi,

print(armstrong(153))
print(armstrong(999))
print(armstrong(371))
print(armstrong(333))


(True,)
(False,)
(True,)
(False,)


In [14]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

birles = A & B
sadece_A = A | B
sirali = sorted(A | B)

print("ortak olanlar", birles)
print("sadece A da olanlar",sadece_A)
print("alfabetik siralama", sirali)

ortak olanlar {'SQL', 'Python'}
sadece A da olanlar {'C++', 'R', 'SQL', 'Python', 'JavaScript', 'Java'}
alfabetik siralama ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [17]:
import random
import statistics

sayi = [random.randint(1,100) for i in range(10)]
ortalama = statistics.mean(sayi)
print(sayi)
print("ortalama",ortalama)
std_sapma = statistics.stdev(sayi)
print("standart sapması",std_sapma)

[38, 16, 2, 22, 87, 12, 45, 27, 79, 50]
ortalama 37.8
standart sapması 28.10219445761013


In [18]:
def kelime_sayici(metin):
  kelimeler = metin.split()
  toplam = len(kelimeler)
  en_uzun = max(kelimeler,key=len)

  en_cok_tekrar = {}
  for i in kelimeler:
    if i in en_cok_tekrar:
      en_cok_tekrar[i] += 1
    else :
      en_cok_tekrar[i] = 1

  bulduk = max(en_cok_tekrar,key=en_cok_tekrar.get)
  return toplam,en_uzun,bulduk

metin = "Bugün hava güneşli ve hava çok güzel insanın iiçini ısıtıyor"
print(kelime_sayici(metin))


(10, 'ısıtıyor', 'hava')


In [25]:
sayilar = [5, 12, 7, 18, 24, 3, 16]
cift = list(filter(lambda x: x%2 == 0,sayilar))
print("çift sayılar",cift)
kare = list(map(lambda x: x**2,cift))
print("sayıların kareleri",kare)
kareler = sorted(sayilar , reverse =True)
print("sayıların karelerinin azdan çoğasıralanmış hali",kareler)

çift sayılar [12, 18, 24, 16]
sayıların kareleri [144, 324, 576, 256]
sayıların karelerinin azdan çoğasıralanmış hali [24, 18, 16, 12, 7, 5, 3]


In [29]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

uzunluk = list(map(lambda x:( len(x),x),kelimeler))
sirali = sorted(uzunluk)
sonuc = list(map(lambda x:x[1],sirali))
print(sonuc)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [33]:
def rakam_bul(metin):
    toplam = 0
    sayi = ""
    for i in metin:
        if i.isdigit():
            sayi += i
        else:
            if sayi:   # sayi boş değilse
                toplam += int(sayi)
                sayi = ""   # sıfırla

    if sayi:   # en son kalan sayı varsa ekle
        toplam += int(sayi)

    return toplam


metin = "salnass5fmv0kffn6f9w5w4"
print(rakam_bul(metin))


29


In [34]:
import numpy as np
dizi = np.random.randint(0,50,10)

ortalama = np.mean(dizi)
std_sapma = np.std(dizi)
en_buyuk = np.max(dizi)

print("sayilar",sayilar)
print("ortalaması",ortalama)
print("standart sapması",std_sapma)
print("en büyük sayi",en_buyuk)

sayilar [5, 12, 7, 18, 24, 3, 16]
ortalaması 19.8
standart sapması 12.820296408429876
en büyük sayi 36


In [35]:
import numpy as np

matris = np.random.rand(5, 5)
print("Orijinal Matris:\n", matris)

sutun_ort = np.mean(matris, axis=0)
print("\nSütun Ortalamaları:\n", sutun_ort)

binary_matris = (matris > 0.5).astype(int)
print("\nBinary Matris:\n", binary_matris)


Orijinal Matris:
 [[0.50314266 0.90531945 0.17902902 0.48502219 0.10133363]
 [0.91848743 0.12306321 0.02998132 0.81451326 0.80995633]
 [0.73913154 0.71509094 0.38446025 0.81789341 0.27098493]
 [0.28780555 0.28878077 0.89098823 0.08856916 0.18117455]
 [0.12099207 0.54850311 0.65338258 0.10327959 0.05363153]]

Sütun Ortalamaları:
 [0.51391185 0.5161515  0.42756828 0.46185552 0.28341619]

Binary Matris:
 [[1 1 0 0 0]
 [1 0 0 1 1]
 [1 1 0 1 0]
 [0 0 1 0 0]
 [0 1 1 0 0]]
